### PR TITLE
Use relative links in README and fix "depecated" spelling error.

### PR DESCRIPTION
**Pull request by dvoiss**
Changes:

* The spelling error "depecated" was only in the `README` and not in the code.
* The table of contents links were absolute links which when clicked brought me back here. I've updated them to be relative links.

### CODE REVIEW

**Comment by rgson** [comment]
Nice! :+1:
I experienced the same issue with the absolute URLs in my earlier fork, but I never actually got around to changing them. IMO this should definitely be included to aid all the forks out there.

**Comment by TheFinestArtist** [comment]
@dvoiss Wow, it is really impressive! I had no idea that I would be able to use relative link!

**Comment by TheFinestArtist** [comment]
@dvoiss Wow, it is really impressive! I had no idea that I would be able to use relative link!

**Comment by TheFinestArtist** [comment]
@dvoiss Let me know if you have any ideas with utils for Android application development! You are always welcome :)

**Pull request merged**
