### PR TITLE
Add PreferenceUtil

### PR DESCRIPTION
**Pull request by rgson**
Hi,

I've created a utility class for managing application-wide preferences in a more convenient way. It's a more meticulously crafted re-implementation of a utility class I've personally found useful in previous projects.

The ``PreferenceUtil`` class offers uniform usage for all of the datatypes supported by ``SharedPreferences`` and adds additional functionality by utilizing serialization to allow for storing of other datatypes as well.

I've included instrumented unit tests and updated the documentation to go along with the new class.

If you think this is a useful addition, I'd be glad to see it included in the main repository.

~ rgson

P.S. I'm not sure how the stars in the README are determined, so those are perhaps incorrect.

### CODE REVIEW

**Comment by TheFinestArtist** [comment]
@rgson Thank you so much for this update. I will release new version right away. This util was what I was looking for next updates! 
Stars are based on usefulness `PreferenceUtil` is 5 stars!

**Comment by TheFinestArtist** [comment]
@rgson Sorry about late release, I want to add one more options to change the preference name which is now just "PreferenceUtil". I will work on this tonight and release new version tonight. It might take 24 hours. I really thanks for your contribution.

**Comment by rgson** [comment]
@TheFinestArtist Absolutely, no problem!

I initially thought about making the preference name configurable actually, but in the end I decided against it. I didn't want to introduce state to the static utility class in case that broke your design philosophy. (As far as I could see, it seemed only Base contained state information.)

One alternative I considered was to add a second set of methods like the ones currently existing, but with an additional first argument specifying the preference name. For example, `int get(String preferences, String key, int defValue);`. Ultimately I wasn't entirely satisfied with that either, though, as proper usage would require the user to keep a `static final String` with their preference name somewhere in their app and pass it to the `PreferenceUtil` every time. It just didn't feel very convenient.

**Comment by TheFinestArtist** [comment]
My initial thought was simply adding `setDefaultName(String name);`. Maybe `removeAll();`

```java
void              setDefaultName(String name);

boolean        get(String key, boolean defValue);
boolean        get(String name, String key, boolean defValue);
...

void              put(String key, boolean value);
void              put(String name, String key, boolean value);
...

void              remove(String... key);
void              remove(String name, String... key);

void              removeAll();
void              removeAll(String name);
```

**Comment by TheFinestArtist** [comment]
I really thanks that you cared about consistency with other utils. But, to be honest with you, I don't really have any good design policy, my main concern is whether each util is easy to use and has enough methods.

**Comment by rgson** [comment]
I think your suggested changes are good. If the introduction of state is not a concern, then `setDefaultName(String name)` is definitely a must-have feature. I also like the idea of a `removeAll()` method. 

If you haven't started implementing the changes yet, then I could do it actually. I figure you probably have other ideas for utilities to spend your time on.

_Off-topic:_ Speaking of other utilities; perhaps it'd be a good idea to register "issues" (feature requests) detailing some of the upcoming utilities you have listed in the README? If you have some ideas as for their planned functionality and interfaces then perhaps someone else (or even me) could help you out with them.

**Comment by TheFinestArtist** [comment]
@rgson It would be really great if you add more methods for `PreferenceUtils`. Since the previous methods you've already made is also included with new methods list, I will release new version with current methods. 

I will move all the upcoming utilities to [Feature Requests] issues. This is really great idea! I added you as collaborator so that you can work seamlessly. Thanks so much!

**Comment by TheFinestArtist** [comment]
Come to think of it. I think `removeAll()` should be `clear()`. Let me know if you have any better answer!
https://docs.oracle.com/javase/7/docs/api/java/util/Map.html

```java
void              setDefaultName(String name);

boolean        get(String key, boolean defValue);
boolean        get(String name, String key, boolean defValue);
...

void              put(String key, boolean value);
void              put(String name, String key, boolean value);
...

void              remove(String... key);
void              remove(String name, String... key);

void              clear();
void              clear(String name);
```

**Pull request merged**
